# Example configuration in YAML
#
databases:
    # Local test database
    postgres:
        enabled: true
        host: postgresql
        port: 5432
        database: postgres
        user: postgres
        password: postgres
        ssl: false

# Notify listeners
# These are used by the pgnotify-rabbitmq.js application which connects
# to each database and adds a notify listener so that postgresql code
# can issue NOTIFY('key','message') and that message is sent to
# a rabbitmq instance
notify:

    -
      # Is this notifier enabled, disabled if absent/ !true
      enabled: true
      # Database to connect to (required)
      database: postgres
      # The notification name to listen to (required)
      # To exceute NOTIFY('rabbitmq','message')
      name: rabbit
      # Log the message and meta data to the console (optional)
      debug: true
      # Convert the payload into json (optional) defaults to false
      json: false
      # Handlers to use. This is a map of handlers and any config they
      # require. The config format is specific to each handler. Also
      # An app doesn't have to support a handler, just define them
      # when calling the notify() method
      handlers:
          # Example handler, logs the payload to the console (optional)
          #console: true
          # Rabbit instance to use
          rabbit:
              instance: local
              # Topic to use, defaults to amq.topic (required if rabbit set)
              topic: amq.fanout
              # key: use just a routing key and send entire message to that key
              key: job.status
              # Valid only if json:true if set then the key in the message
              # containing the routing key
              #routingKey: key.test
              # Valid only when routingKey is valid, the key of the message
              # containing the actual message. If missing then the original
              # message is sent instead
              #payload: body
    -
      enabled: true
      database: postgres
      name: http
      debug: true
      json: true
      handlers:
        http
    -
      enabled: true
      database: postgres
      name: fcm
      debug: true
      json: true
      handlers:
        # for more info link to: https://www.npmjs.com/package/firebase-admin
        fcm:
          clientEmail: firebase-adminsdk-v4349@****-*****-663a5.iam.gserviceaccount.com
          projectId: fooo-project-id
          privateKey:


# RabbitMQ configuration
rabbit:
    # Test rabbit instance with user guest, password guest on localhost.
    # You can put an IP address here, for IPv6 enclose the address with []
    local: amqp://rabbit:rabbit@rabbitmq/TEST?heartbeat=30